name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup DB
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 'latest'
          mysql database: 'test-db'
          mysql user: 'root'
          mysql password: '123456'

      - name: Build
        run: mvn clean package -DskipTests=true

      - name: Run unit tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install -DskipTests